web:
    image: nginx:latest
    ports:
        - "8080:80"
    volumes:
        - .:/code
        - ./env/site.conf:/etc/nginx/conf.d/site.conf
        - ../logs:/var/log/rankster
    links:
        - php
php:
    build: .
    dockerfile: docker/Dockerfile-php
    volumes:
        - .:/code
    links:
        - mysql
mysql:
    image: mariadb:latest
    environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=rankster
    volumes:
        - ../database:/var/lib/mysql
cli:
    build: .
    dockerfile: docker/Dockerfile-php-cli
    volumes:
        - .:/code
    links:
        - mysql
    command: sleep 10 && /code/bin/tool migrate
